name: Python application

on:
  push:
    branches:
      - main
      - feature/**
      - feacture/**

  pull_request:
    branches: ["main"]

jobs:
  build-python-workflow:
    name: "Build application"
    permissions:
      checks: write # Required for CodeCoverageSummary
      pull-requests: write # Required for CodeCoverageSummary
      contents: read # Required for CodeCoverageSummary
    uses: artm-devsecops/artm-workflow-templates/.github/workflows/artm-devsecops-build-python.yml@main
    with:
      python_version: 3.10

  build-image-workflow:
    name: "Build image"
    needs: build-python-workflow
    permissions:
      packages: write # Required for Container
      security-events: write # Required for Scanning
    uses: artm-devsecops/artm-workflow-templates/.github/workflows/artm-devsecops-build-image.yml@main
    with:
      image_tag: "v1"
      image_context: "."
      image_files: "Dockerfile"
      container_registry: "ghcr.io"
